export enum UserState {
  SIGNUP_OAUTH_COMPLETED = "SIGNUP_OAUTH_COMPLETED",
  SIGNUP_ALL_COMPLETED = "SIGNUP_ALL_COMPLETED",
  SIGNUP_OAUTH_CREDIT_CARD_COMPLETED = "SIGNUP_OAUTH_CREDIT_CARD_COMPLETED",
}
